name: Matrix Job with Summary

on: [push, pull_request]

jobs:
  matrix-job:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Run tests
        run: |
          if [[ ${{ matrix.node-version }} == "16" ]]; then
            echo "Simulating failure" && exit 1
          fi
          echo "Tests passed for Node.js ${{ matrix.node-version }}"

  summary-job:
    needs: matrix-job
    runs-on: ubuntu-24.04
    if: always()  # Ensure this runs even if matrix-job fails
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq  # Needed for JSON parsing

      - name: Fetch job statuses using GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
        run: |
          echo "### Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Node.js Version | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|----------------|--------|" >> $GITHUB_STEP_SUMMARY

          # Fetch all jobs in the current workflow run
          JOBS_JSON=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github+json" \
                              "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/jobs")

          # Track failure flag
          JOB_FAILED=false

          # Extract statuses dynamically
          for version in 14 16 18; do
            JOB_STATUS=$(echo "$JOBS_JSON" | jq -r ".jobs[] | select(.name | contains(\"$version\")) | .conclusion")
            if [[ "$JOB_STATUS" == "success" ]]; then
              echo "| $version | ✅ Success |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| $version | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
              JOB_FAILED=true
            fi
          done

          # Fail the job if any matrix job failed
          if [[ "$JOB_FAILED" == "true" ]]; then
            echo "One or more matrix jobs failed. Failing summary job."
            exit 1
          fi