# Example workflow running in windows-2022 when dispatched
name: Test WSL

on:
  workflow_dispatch:

jobs:
  test-wsl-execution:
    name: Test WSL
    runs-on: windows-2022
    steps:
      - name: Run on WSL
        uses: Vampire/setup-wsl@v4
        with:
          distribution: Ubuntu-24.04
          set-as-default: true
    
      - name: Test commands
        shell: wsl-bash {0}
        run: |
            cat /etc/issue.net
            uname -a
