# Example workflow running in windows-2022 when dispatched
name: Test WSL NO ACTION

on:
  workflow_dispatch:


jobs:
  test-wsl-execution:
    name: Test WSL NO ACTION
    runs-on: windows-2022
    steps:
      - name: Setup WSL
        run: wsl --install -d Ubuntu-24.04
      
      - name: List installed WSL
        run: wsl --list --all
      
      - name: Run on WSL
        run: wsl -d Ubuntu-24.04 -- bash -c "cat /etc/issue.net && uname -a"
    